services:
  radarr_fr:
    image: linuxserver/radarr
    container_name: radarr_fr
    ports:
      - 7879:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - /srv/media-stack:/data
    restart: unless-stopped